### ISSUE TITLE
[Request] Print a string when no windows are open on the desktop

### ISSUE THREAD

**Issue by loki7990** [alnj/polywins#3]
Hello,

I was wondering if it would be possible to print a configured string such as "Desktop" when there are no currently opened windows on the focused desktop? It seemed like it would be simple but I couldn't quite figure out how to implement it myself

**Comment by alnj** [comment]
Hey there, sorry I didn't see this. I'm new to Github and somehow didn't see any notification for activity in this repo.

I've just released a major overhaul to Polywins, which includes this feature. Thanks for the idea.
